### PR TITLE
Add instruction on enabling chef-guard in Chef 12

### PR DESCRIPTION
**Pull request by iroller**

### CODE REVIEW

**Comment by svanharmelen** [comment]
Does Chef 12 has a private mode? Does it than also have a Enterprise mode? As I thought it was only one install with Enterprise features that could be turned on or off. In which case we should reformat the text a little to just `Chef 12`

**Comment by iroller** [comment]
Well when it was only Chef 11 we called it:
* Enterprise Chef 11
* Open Source Chef Server 11

Now since Chef 12 is the only one and opensourced we call it:
* Hosted Chef 12
* Private Chef 12 or Chef 12

We can make it saying just "Chef 12" if you think it's better.

**Comment by svanharmelen** [comment]
Yeah, for me Private Chef refers to Enterprise Chef, which was first called Private Chef before being rebranded to Enterprise Chef.

And since they heavily invested in making it public knowledge, there is now only one Chef 12 server... So let's just call it Chef 12 in this case.

Note: Not talking about Hosted Chef (which is simply a SaaS offering based on the same Chef 12 server software), as you cannot configure/use CG with that anyway...

**Comment by iroller** [comment]
Ok, now it's saying just "Chef 12"

**Pull request merged**
